# Linear Algebra- Problem Solving

In [2]:
import numpy as np

In [3]:
# Taking a 3x3 matrix
w = np.array([[ 1, 2, -1],
             [1, 0, 1],
             [ 0, 1, 0 ]])
w

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 0,  1,  0]])

In [4]:
# Calculating inverse of the matrix
print(np.linalg.inv(w))

[[ 0.5  0.5 -1. ]
 [-0.  -0.   1. ]
 [-0.5  0.5  1. ]]


# Determinant of Matrix

In [11]:
det = np.linalg.det(w)
det

-2.0

# Matrix Multiplication

In [6]:
# Taking a 3x3 matrix = A
a = np.array([[5, 2, 3],
             [-1, -3, 2],
             [0, 1, -1]])
a

array([[ 5,  2,  3],
       [-1, -3,  2],
       [ 0,  1, -1]])

In [7]:
# Taking a 3x3 matrix = B
b = np.array([[1, 0, -4], 
             [2, 1, 0],
             [8, -1, 0]])
b

array([[ 1,  0, -4],
       [ 2,  1,  0],
       [ 8, -1,  0]])

In [9]:
result = np.dot(a,b)
result

array([[ 33,  -1, -20],
       [  9,  -5,   4],
       [ -6,   2,   0]])